os: windows
language: bash
services: docker
script: 
  - echo hi
  - net stop dockerd
  - docker version
  #- "\"C:\\Program Files\\Docker\\Docker\\DockerCli.exe\" -SwitchDaemon"
  - docker run --platform linux alpine sleep 10
 
