os: windows
language: bash
services: docker
script: 
  - echo hi
  #- net stop docker
  - docker version
  - ls /c/
  - cat /c/ProgramData/docker/config/daemon.json
  # "experimental": true
  - "\"/c/Program Files/Docker/Docker/DockerCli.exe\" -SwitchDaemon"
  - docker version
  - docker run --platform linux alpine sleep 10
 
