os: windows
language: bash
services: docker
script: 
  #- echo hi
  #- docker version
  #- wget -q https://github.com/friism/linuxkit/releases/download/preview-1/linuxkit.zip
  #- unzip linuxkit.zip -d "/c/Program Files/Linux Containers/"
  # - wget -q https://github.com/linuxkit/lcow/releases/download/v4.14.35-v0.3.9/release.zip
  # - unzip release.zip -d "/c/Program Files/Linux Containers/"
  #- net stop docker
  #- dockerd --experimental  2>&1 >log.txt &
  #- ls "/c/Program Files/"
  #- ls "/c/Program Files/Docker"
  #- ls /c/ProgramData/docker/config
  #- cat /c/ProgramData/docker/config/daemon.json
  # "experimental": true
  #- "\"/c/Program Files/Docker/Docker/DockerCli.exe\" -SwitchDaemon"
  #- docker version
  - echo hello > hello.txt
  - echo docker  -v "$(pwd):$(pwd)" -w "$(pwd)" run abrarov/mingw cat hello.txt
  - docker  -v "$(pwd):$(pwd)" -w "$(pwd)" run abrarov/mingw cat hello.txt

 
