os: windows
language: bash
services: docker
script: 
  - echo hi
  #- net stop docker
  - docker version
  - "/Program Files/Docker/Docker/DockerCli.exe" -SwitchDaemon"
  - docker version
  - docker run --platform linux alpine sleep 10
 
